packages:
  - 'automa-cli'
  - 'automa-vscode'
  - 'automa-ext'
  - 'packages/*'
allowBuilds:
  better-sqlite3: true
  core-js: set this to true or false
  esbuild: true
  puppeteer: true
  simple-git-hooks: set this to true or false
  vue-demi: set this to true or false
