packages:
  - 'automa-vsce'
  - 'automa-webe'
  - 'automa-desk'
  - 'packages/*'
allowBuilds:
  core-js: true
  esbuild: true
  puppeteer: true
  simple-git-hooks: true
  vue-demi: true
  es5-ext: true
  unrs-resolver: true
  better-sqlite3: true
minimumReleaseAge: 0
