packages:
  - 'automa-cli'
  - 'automa-vscode'
  - 'automa-ext'
  - 'packages/*'
allowBuilds:
  better-sqlite3: true
  core-js: true
  esbuild: true
  puppeteer: true
  simple-git-hooks: true
  vue-demi: true
  es5-ext: true
  unrs-resolver: true
minimumReleaseAge: 0
