// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8765' | (string & {});
};

export type ActiveJobResponse = {
    jobId: string;
};

export type AddTableRowPayload = {
    [key: string]: unknown;
};

export type AddTableRowResponse = {
    id: string;
    tableId: string;
};

export type ApiErrorResponse = {
    error: string;
    status: number;
};

export type AppSettings = {
    browser: BrowserSettings;
    grid: GridSettings;
    runner: RunnerSettings;
};

export type Browser = {
    created_at: string;
    id: string;
    name: string;
    timezone?: string | null;
    updated_at: string;
    user_agent?: string | null;
};

export type BrowserResponse = {
    createdAt: string;
    id: string;
    isOnline: boolean;
    name: string;
    timezone?: string | null;
    updatedAt: string;
    userAgent?: string | null;
};

export type BrowserSettings = {
    default_type: string;
    default_user_agent?: string | null;
    executable_path?: string | null;
    headless: boolean;
};

export type Cookie = {
    domain: string;
    expirationDate?: number | null;
    hostOnly?: boolean | null;
    httpOnly?: boolean | null;
    id?: number | null;
    name: string;
    path: string;
    sameSite?: string | null;
    secure?: boolean | null;
    session?: boolean | null;
    storeId?: string | null;
    value: string;
};

export type CreateBrowserRequest = {
    id?: string | null;
    name: string;
    timezone?: string | null;
    userAgent?: string | null;
};

export type DisplaySettings = {
    margin: number;
    monitor_index: number;
    offset_x: number;
    offset_y: number;
    screen_height: number;
    screen_width: number;
};

export type EncryptSecretRequest = {
    passphrase?: string | null;
    plaintext: string;
};

export type EncryptSecretResponse = {
    encrypted_secret: string;
};

export type GridBehavior = {
    auto_recycle_slots: boolean;
    enforce_cdp_bounds: boolean;
    scale_factor: number;
};

export type GridMatrix = {
    columns: number;
    rows: number;
};

export type GridSettings = {
    behavior: GridBehavior;
    display: DisplaySettings;
    enabled: boolean;
    matrix: GridMatrix;
};

export type HealthResponse = {
    message: string;
    status: string;
    version: string;
};

export type HistoryActionResponse = {
    message: string;
    success: boolean;
};

export type ImportCsvPayload = {
    csv_string: string;
};

export type ImportCsvResponse = {
    message: string;
    status: string;
};

export type JobDetails = {
    error?: string | null;
    job?: null | JobInfo;
    logs?: Array<unknown> | null;
    results?: unknown;
};

export type JobHistoryItem = {
    createdAt: string;
    id: string;
    name: string;
    status: string;
    updatedAt: string;
};

export type JobInfo = {
    createdAt: string;
    duration?: number | null;
    endedAt: string;
    id: string;
    name: string;
    status: string;
    workflowId: string;
};

export type JobLogPayload = {
    logs?: Array<{
        [key: string]: unknown;
    }> | null;
    message?: string | null;
    type: string;
};

export type JobStatusResponse = {
    status: string;
};

export type LintIssue = {
    message: string;
    path?: string | null;
    severity: string;
};

export type LintRequest = {
    edges?: Array<{
        [key: string]: unknown;
    }> | null;
    nodes?: Array<{
        [key: string]: unknown;
    }> | null;
};

export type LintResponse = {
    issues: Array<LintIssue>;
    valid: boolean;
};

export type LogItem = {
    createdAt: string;
    id: number;
    jobId: string;
    message: string;
    type: string;
};

export type MatrixStatusResponse = {
    campaignId: string;
    completedTasks: number;
    status: string;
    totalTasks: number;
};

export type RunnerSettings = {
    auto_clean_history_days: number;
    max_concurrent_jobs: number;
    timeout_ms: number;
};

export type SideloadExtensionPayload = {
    extension_path: string;
};

export type SideloadExtensionResponse = {
    message: string;
    status: string;
};

export type StorageCredential = {
    id?: string | null;
    key?: string | null;
    name?: string | null;
    value: string;
};

export type StorageTable = {
    columns?: {
        [key: string]: unknown;
    } | null;
    columnsIndex?: {
        [key: string]: unknown;
    } | null;
    createdAt?: number | null;
    id?: string | null;
    items?: {
        [key: string]: unknown;
    } | null;
    modifiedAt?: number | null;
    name?: string | null;
};

export type StorageVariable = {
    id?: string | null;
    key?: string | null;
    name?: string | null;
    value: {
        [key: string]: unknown;
    };
};

export type SubmitJobOptions = {
    /**
     * Target browser browser ID
     */
    browserId?: string | null;
    /**
     * Close browser when workflow finishes
     */
    closeBrowserOnFinish?: boolean | null;
    /**
     * Enable debug mode
     */
    debug?: boolean | null;
    /**
     * Default browser executable type (chromium, chrome, edge, etc)
     */
    defaultBrowser?: string | null;
    /**
     * Run browser in headless mode
     */
    headless?: boolean | null;
    /**
     * Variables to inject into the workflow
     */
    variables?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Payload for submitting a new background job
 */
export type SubmitJobPayload = {
    options?: null | SubmitJobOptions;
    /**
     * Absolute or relative path to the `.workflow.json` file.
     */
    workflowPath: string;
};

export type SubmitJobResponse = {
    jobId: string;
    message?: string | null;
    status: string;
};

export type SystemMetricsResponse = {
    activeRunners: number;
    cpuUsage: number;
    memoryFree: number;
    memoryTotal: number;
};

export type SystemResponse = {
    message: string;
    success: boolean;
};

export type TableRow = {
    data: {
        [key: string]: unknown;
    };
    id: string;
    table_id: string;
};

export type UpdateAppSettingsRequest = {
    browser?: null | UpdateBrowserSettingsRequest;
    grid?: null | UpdateGridSettingsRequest;
    runner?: null | UpdateRunnerSettingsRequest;
};

export type UpdateBrowserRequest = {
    name?: string | null;
    timezone?: string | null;
    userAgent?: string | null;
};

export type UpdateBrowserSettingsRequest = {
    default_type?: string | null;
    default_user_agent?: string | null;
    executable_path?: string | null;
    headless?: boolean | null;
};

export type UpdateDisplaySettingsRequest = {
    margin?: number | null;
    monitor_index?: number | null;
    offset_x?: number | null;
    offset_y?: number | null;
    screen_height?: number | null;
    screen_width?: number | null;
};

export type UpdateGridBehaviorRequest = {
    auto_recycle_slots?: boolean | null;
    enforce_cdp_bounds?: boolean | null;
    scale_factor?: number | null;
};

export type UpdateGridMatrixRequest = {
    columns?: number | null;
    rows?: number | null;
};

export type UpdateGridSettingsRequest = {
    behavior?: null | UpdateGridBehaviorRequest;
    display?: null | UpdateDisplaySettingsRequest;
    enabled?: boolean | null;
    matrix?: null | UpdateGridMatrixRequest;
};

export type UpdateRunnerSettingsRequest = {
    auto_clean_history_days?: number | null;
    max_concurrent_jobs?: number | null;
    timeout_ms?: number | null;
};

export type GetBrowsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/browsers';
};

export type GetBrowsersErrors = {
    /**
     * Database error
     */
    500: unknown;
};

export type GetBrowsersResponses = {
    /**
     * List of all browsers
     */
    200: Array<BrowserResponse>;
};

export type GetBrowsersResponse = GetBrowsersResponses[keyof GetBrowsersResponses];

export type CreateBrowserData = {
    body: CreateBrowserRequest;
    path?: never;
    query?: never;
    url: '/api/browsers';
};

export type CreateBrowserErrors = {
    /**
     * Invalid input or browser ID
     */
    400: unknown;
    /**
     * Failed to create browser
     */
    500: unknown;
};

export type CreateBrowserResponses = {
    /**
     * Browser created successfully
     */
    200: unknown;
};

export type ImportBrowsersCsvData = {
    body: ImportCsvPayload;
    path?: never;
    query?: never;
    url: '/api/browsers/import-csv';
};

export type ImportBrowsersCsvResponses = {
    /**
     * Imported
     */
    200: ImportCsvResponse;
};

export type ImportBrowsersCsvResponse = ImportBrowsersCsvResponses[keyof ImportBrowsersCsvResponses];

export type KillBrowsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/browsers/sessions';
};

export type KillBrowsersResponses = {
    /**
     * Browsers killed successfully
     */
    200: SystemResponse;
};

export type KillBrowsersResponse = KillBrowsersResponses[keyof KillBrowsersResponses];

export type DeleteBrowserData = {
    body?: never;
    path: {
        /**
         * Browser ID
         */
        id: string;
    };
    query?: never;
    url: '/api/browsers/{id}';
};

export type DeleteBrowserErrors = {
    /**
     * Invalid browser ID
     */
    400: unknown;
    /**
     * Browser not found
     */
    404: unknown;
    /**
     * Failed to delete browser
     */
    500: unknown;
};

export type DeleteBrowserResponses = {
    /**
     * Browser deleted successfully
     */
    200: unknown;
};

export type GetBrowserDetailData = {
    body?: never;
    path: {
        /**
         * Browser ID
         */
        id: string;
    };
    query?: never;
    url: '/api/browsers/{id}';
};

export type GetBrowserDetailErrors = {
    /**
     * Invalid browser ID
     */
    400: unknown;
    /**
     * Browser not found
     */
    404: unknown;
    /**
     * Failed to fetch browser
     */
    500: unknown;
};

export type GetBrowserDetailResponses = {
    /**
     * Browser details
     */
    200: BrowserResponse;
};

export type GetBrowserDetailResponse = GetBrowserDetailResponses[keyof GetBrowserDetailResponses];

export type UpdateBrowserData = {
    body: UpdateBrowserRequest;
    path: {
        /**
         * Browser ID
         */
        id: string;
    };
    query?: never;
    url: '/api/browsers/{id}';
};

export type UpdateBrowserErrors = {
    /**
     * Invalid browser ID
     */
    400: unknown;
    /**
     * Browser not found
     */
    404: unknown;
    /**
     * Failed to update browser
     */
    500: unknown;
};

export type UpdateBrowserResponses = {
    /**
     * Browser updated successfully
     */
    200: unknown;
};

export type GetCookiesData = {
    body?: never;
    path: {
        /**
         * Browser ID
         */
        id: string;
    };
    query?: never;
    url: '/api/browsers/{id}/cookies';
};

export type GetCookiesErrors = {
    /**
     * Failed to export cookies
     */
    500: unknown;
};

export type GetCookiesResponses = {
    /**
     * Exported cookies
     */
    200: Array<Cookie>;
};

export type GetCookiesResponse = GetCookiesResponses[keyof GetCookiesResponses];

export type PostCookiesData = {
    body: Array<Cookie>;
    path: {
        /**
         * Browser ID
         */
        id: string;
    };
    query?: never;
    url: '/api/browsers/{id}/cookies';
};

export type PostCookiesErrors = {
    /**
     * Failed to import cookies
     */
    500: unknown;
};

export type PostCookiesResponses = {
    /**
     * Cookies imported successfully
     */
    200: unknown;
};

export type SideloadExtensionData = {
    body: SideloadExtensionPayload;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/browsers/{id}/extensions';
};

export type SideloadExtensionResponses = {
    /**
     * Sideloaded
     */
    200: SideloadExtensionResponse;
};

export type SideloadExtensionResponse2 = SideloadExtensionResponses[keyof SideloadExtensionResponses];

export type StopBrowserData = {
    body?: never;
    path: {
        /**
         * Browser ID
         */
        id: string;
    };
    query?: never;
    url: '/api/browsers/{id}/session';
};

export type StopBrowserResponses = {
    /**
     * Browser session terminated
     */
    200: unknown;
};

export type StartBrowserData = {
    body?: never;
    path: {
        /**
         * Browser ID
         */
        id: string;
    };
    query?: never;
    url: '/api/browsers/{id}/session';
};

export type StartBrowserErrors = {
    /**
     * Invalid browser ID
     */
    400: unknown;
    /**
     * Failed to start browser session
     */
    500: unknown;
};

export type StartBrowserResponses = {
    /**
     * Browser session started
     */
    200: unknown;
};

export type GetMatrixStatusData = {
    body?: never;
    path: {
        /**
         * Campaign ID
         */
        id: string;
    };
    query?: never;
    url: '/api/campaigns/{id}/matrix-status';
};

export type GetMatrixStatusErrors = {
    /**
     * Campaign not found
     */
    404: unknown;
};

export type GetMatrixStatusResponses = {
    /**
     * Matrix status retrieved
     */
    200: MatrixStatusResponse;
};

export type GetMatrixStatusResponse = GetMatrixStatusResponses[keyof GetMatrixStatusResponses];

export type SseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type SseResponses = {
    /**
     * Server-Sent Events stream for task logs and progress
     */
    200: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Check daemon health status
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type ClearHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/history';
};

export type ClearHistoryErrors = {
    /**
     * Database or thread pool failure
     */
    500: unknown;
};

export type ClearHistoryResponses = {
    /**
     * All job history cleared successfully
     */
    200: HistoryActionResponse;
};

export type ClearHistoryResponse = ClearHistoryResponses[keyof ClearHistoryResponses];

export type GetHistoryData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number | null;
    };
    url: '/api/history';
};

export type GetHistoryErrors = {
    /**
     * Database or thread pool failure
     */
    500: unknown;
};

export type GetHistoryResponses = {
    /**
     * Get job history
     */
    200: Array<JobHistoryItem>;
};

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses];

export type DeleteHistoryItemData = {
    body?: never;
    path: {
        /**
         * Job ID to delete
         */
        job_id: string;
    };
    query?: never;
    url: '/api/history/{job_id}';
};

export type DeleteHistoryItemErrors = {
    /**
     * Database or thread pool failure
     */
    500: unknown;
};

export type DeleteHistoryItemResponses = {
    /**
     * Job history deleted successfully
     */
    200: HistoryActionResponse;
};

export type DeleteHistoryItemResponse = DeleteHistoryItemResponses[keyof DeleteHistoryItemResponses];

export type GetLogsData = {
    body?: never;
    path: {
        /**
         * Job ID to fetch logs for
         */
        job_id: string;
    };
    query?: never;
    url: '/api/history/{job_id}/logs';
};

export type GetLogsErrors = {
    /**
     * Database or thread pool failure
     */
    500: unknown;
};

export type GetLogsResponses = {
    /**
     * Get job logs
     */
    200: JobDetails;
};

export type GetLogsResponse = GetLogsResponses[keyof GetLogsResponses];

export type ListenToWorkerEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/worker/events';
};

export type ListenToWorkerEventsResponses = {
    /**
     * SSE Stream for Worker jobs
     */
    200: unknown;
};

export type GetActiveJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type GetActiveJobsResponses = {
    /**
     * List of active jobs
     */
    200: Array<ActiveJobResponse>;
};

export type GetActiveJobsResponse = GetActiveJobsResponses[keyof GetActiveJobsResponses];

export type SubmitJobData = {
    body: SubmitJobPayload;
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type SubmitJobErrors = {
    /**
     * Invalid request payload or file
     */
    400: unknown;
    /**
     * Browser worker unavailable
     */
    503: unknown;
};

export type SubmitJobResponses = {
    /**
     * Job submitted successfully
     */
    200: SubmitJobResponse;
};

export type SubmitJobResponse2 = SubmitJobResponses[keyof SubmitJobResponses];

export type KillJobData = {
    body?: never;
    path: {
        /**
         * Job ID
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}';
};

export type KillJobErrors = {
    /**
     * Job not found or not active
     */
    404: unknown;
};

export type KillJobResponses = {
    /**
     * Job killed successfully
     */
    200: unknown;
};

export type AppendJobLogsData = {
    body: JobLogPayload;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}/logs';
};

export type AppendJobLogsResponses = {
    /**
     * Log received
     */
    200: unknown;
};

export type GetJobStatusData = {
    body?: never;
    path: {
        /**
         * Job ID
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}/status';
};

export type GetJobStatusResponses = {
    /**
     * Job status
     */
    200: JobStatusResponse;
};

export type GetJobStatusResponse = GetJobStatusResponses[keyof GetJobStatusResponses];

export type FinishJobData = {
    body?: never;
    path: {
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}/status';
};

export type FinishJobErrors = {
    /**
     * Job not found or not active
     */
    404: unknown;
};

export type FinishJobResponses = {
    /**
     * Job marked as finished
     */
    200: unknown;
};

export type LintWorkflowData = {
    body: LintRequest;
    path?: never;
    query?: never;
    url: '/api/lint';
};

export type LintWorkflowResponses = {
    /**
     * Linting results
     */
    200: LintResponse;
};

export type LintWorkflowResponse = LintWorkflowResponses[keyof LintWorkflowResponses];

export type EncryptSecretData = {
    body: EncryptSecretRequest;
    path?: never;
    query?: never;
    url: '/api/secrets/encryption';
};

export type EncryptSecretErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type EncryptSecretResponses = {
    /**
     * Secret encrypted successfully
     */
    200: EncryptSecretResponse;
};

export type EncryptSecretResponse2 = EncryptSecretResponses[keyof EncryptSecretResponses];

export type GetCredentialsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storage/credentials';
};

export type GetCredentialsResponses = {
    /**
     * List credentials
     */
    200: Array<StorageCredential>;
};

export type GetCredentialsResponse = GetCredentialsResponses[keyof GetCredentialsResponses];

export type AddCredentialData = {
    body: StorageCredential;
    path?: never;
    query?: never;
    url: '/api/storage/credentials';
};

export type AddCredentialResponses = {
    /**
     * Add credential
     */
    200: StorageCredential;
};

export type AddCredentialResponse = AddCredentialResponses[keyof AddCredentialResponses];

export type DeleteCredentialData = {
    body?: never;
    path: {
        /**
         * Credential ID or Name
         */
        id: string;
    };
    query?: never;
    url: '/api/storage/credentials/{id}';
};

export type DeleteCredentialResponses = {
    /**
     * Credential deleted
     */
    200: unknown;
};

export type GetTablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storage/tables';
};

export type GetTablesErrors = {
    /**
     * Database error
     */
    500: unknown;
};

export type GetTablesResponses = {
    /**
     * List tables
     */
    200: Array<StorageTable>;
};

export type GetTablesResponse = GetTablesResponses[keyof GetTablesResponses];

export type AddTableData = {
    body: StorageTable;
    path?: never;
    query?: never;
    url: '/api/storage/tables';
};

export type AddTableErrors = {
    /**
     * Database error
     */
    500: unknown;
};

export type AddTableResponses = {
    /**
     * Add table
     */
    200: StorageTable;
};

export type AddTableResponse = AddTableResponses[keyof AddTableResponses];

export type DeleteTableData = {
    body?: never;
    path: {
        /**
         * Table ID
         */
        id: string;
    };
    query?: never;
    url: '/api/storage/tables/{id}';
};

export type DeleteTableErrors = {
    /**
     * Database error
     */
    500: unknown;
};

export type DeleteTableResponses = {
    /**
     * Table deleted
     */
    200: unknown;
};

export type GetTableRowsData = {
    body?: never;
    path: {
        /**
         * Table ID
         */
        id: string;
    };
    query?: never;
    url: '/api/storage/tables/{id}/rows';
};

export type GetTableRowsErrors = {
    /**
     * Database error
     */
    500: unknown;
};

export type GetTableRowsResponses = {
    /**
     * List table rows
     */
    200: Array<TableRow>;
};

export type GetTableRowsResponse = GetTableRowsResponses[keyof GetTableRowsResponses];

export type AddTableRowData = {
    body: AddTableRowPayload;
    path: {
        /**
         * Table ID
         */
        id: string;
    };
    query?: never;
    url: '/api/storage/tables/{id}/rows';
};

export type AddTableRowErrors = {
    /**
     * Database error
     */
    500: unknown;
};

export type AddTableRowResponses = {
    /**
     * Add table row
     */
    200: AddTableRowResponse;
};

export type AddTableRowResponse2 = AddTableRowResponses[keyof AddTableRowResponses];

export type GetVariablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storage/variables';
};

export type GetVariablesResponses = {
    /**
     * List variables
     */
    200: Array<StorageVariable>;
};

export type GetVariablesResponse = GetVariablesResponses[keyof GetVariablesResponses];

export type AddVariableData = {
    body: StorageVariable;
    path?: never;
    query?: never;
    url: '/api/storage/variables';
};

export type AddVariableResponses = {
    /**
     * Add variable
     */
    200: StorageVariable;
};

export type AddVariableResponse = AddVariableResponses[keyof AddVariableResponses];

export type DeleteVariableData = {
    body?: never;
    path: {
        /**
         * Variable ID or Name
         */
        id: string;
    };
    query?: never;
    url: '/api/storage/variables/{id}';
};

export type DeleteVariableResponses = {
    /**
     * Variable deleted
     */
    200: unknown;
};

export type InstallBrowserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/browser-binaries';
};

export type InstallBrowserResponses = {
    /**
     * Browser installed successfully
     */
    200: SystemResponse;
};

export type InstallBrowserResponse = InstallBrowserResponses[keyof InstallBrowserResponses];

export type GetMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/metrics';
};

export type GetMetricsResponses = {
    /**
     * System metrics retrieved
     */
    200: SystemMetricsResponse;
};

export type GetMetricsResponse = GetMetricsResponses[keyof GetMetricsResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/settings';
};

export type GetSettingsResponses = {
    /**
     * Get current application and grid settings
     */
    200: AppSettings;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type PatchSettingsData = {
    body: UpdateAppSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/system/settings';
};

export type PatchSettingsResponses = {
    /**
     * Partially update application settings
     */
    200: AppSettings;
};

export type PatchSettingsResponse = PatchSettingsResponses[keyof PatchSettingsResponses];

export type UpdateSettingsData = {
    body: AppSettings;
    path?: never;
    query?: never;
    url: '/api/system/settings';
};

export type UpdateSettingsResponses = {
    /**
     * Overwrite application settings
     */
    200: AppSettings;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type OpenStudioData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/studio/session';
};

export type OpenStudioResponses = {
    /**
     * Studio opened successfully
     */
    200: SystemResponse;
};

export type OpenStudioResponse = OpenStudioResponses[keyof OpenStudioResponses];

export type GetWorkflowData = {
    body?: never;
    path?: never;
    query?: {
        path?: string;
    };
    url: '/api/v1/storage/workflow';
};

export type GetWorkflowResponses = {
    200: any;
};

export type SaveWorkflowData = {
    body?: {
        path?: string;
        content?: any;
    };
    path?: never;
    query?: never;
    url: '/api/v1/storage/workflow';
};

export type SaveWorkflowResponses = {
    200: any;
};

export type ListStorageFilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/storage/files';
};

export type ListStorageFilesResponses = {
    200: Array<any>;
};

