// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Active running job descriptor
 */
export type ActiveJobResponse = {
    /**
     * Unique job identifier
     */
    jobId: string;
};

/**
 * Dynamic column values for the row
 */
export type AddTableRowPayload = {
    [key: string]: unknown;
};

/**
 * Response returned after appending a row to a storage table
 */
export type AddTableRowResponse = {
    /**
     * Newly assigned row identifier
     */
    id: string;
    /**
     * Parent table identifier
     */
    tableId: string;
};

export type ApiErrorResponse = {
    error: string;
    status: number;
};

export type AppSettings = {
    browser: BrowserSettings;
    grid: GridSettings;
    runner: RunnerSettings;
};

export type Browser = {
    created_at: string;
    id: string;
    name: string;
    timezone?: string | null;
    updated_at: string;
    user_agent?: string | null;
};

/**
 * Browser profile descriptor
 */
export type BrowserResponse = {
    /**
     * Creation timestamp (ISO 8601)
     */
    createdAt: string;
    /**
     * Unique browser profile identifier
     */
    id: string;
    /**
     * Whether an active browser process is currently connected
     */
    isOnline: boolean;
    /**
     * User-friendly profile label
     */
    name: string;
    /**
     * Emulated timezone ID
     */
    timezone?: string | null;
    /**
     * Last update timestamp (ISO 8601)
     */
    updatedAt: string;
    /**
     * Custom User-Agent header string
     */
    userAgent?: string | null;
};

export type BrowserSettings = {
    default_profile_id?: string | null;
    default_type: string;
    default_user_agent?: string | null;
    executable_path?: string | null;
    headless: boolean;
};

/**
 * Campaign descriptor stored in central SQLite database
 */
export type CampaignStorageItem = {
    /**
     * Creation timestamp (ISO 8601)
     */
    createdAt: string;
    /**
     * Optional cron schedule expression
     */
    cron?: string | null;
    /**
     * Campaign data (members, tasks, matrix, concurrency settings)
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Optional campaign description
     */
    description?: string | null;
    /**
     * Unique campaign identifier
     */
    id: string;
    /**
     * Campaign display name
     */
    name: string;
    /**
     * Last modification timestamp (ISO 8601)
     */
    updatedAt: string;
    /**
     * Semantic version
     */
    version: string;
};

export type Cookie = {
    domain: string;
    expirationDate?: number | null;
    hostOnly?: boolean | null;
    httpOnly?: boolean | null;
    id?: number | null;
    name: string;
    path: string;
    sameSite?: string | null;
    secure?: boolean | null;
    session?: boolean | null;
    storeId?: string | null;
    value: string;
};

/**
 * Request payload for creating a new browser profile
 */
export type CreateBrowserRequest = {
    /**
     * Optional custom ID (auto-generated UUID if omitted)
     */
    id?: string | null;
    /**
     * User-friendly profile name
     */
    name: string;
    /**
     * Emulated timezone ID
     */
    timezone?: string | null;
    /**
     * Custom User-Agent header
     */
    userAgent?: string | null;
};

/**
 * Request payload for creating a new campaign in SQLite database
 */
export type CreateCampaignStorageRequest = {
    /**
     * Optional cron expression
     */
    cron?: string | null;
    /**
     * Campaign data (members, tasks, matrix)
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Optional campaign description
     */
    description?: string | null;
    /**
     * Optional custom identifier
     */
    id?: string | null;
    /**
     * Campaign display name
     */
    name: string;
    /**
     * Optional version (defaults to 1.0.0)
     */
    version?: string | null;
};

/**
 * Request payload for creating a new workflow in SQLite database
 */
export type CreateWorkflowStorageRequest = {
    /**
     * Workflow graph AST (nodes, edges, settings)
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Optional workflow description
     */
    description?: string | null;
    /**
     * Optional UI icon name
     */
    icon?: string | null;
    /**
     * Optional custom identifier (auto-generated if omitted)
     */
    id?: string | null;
    /**
     * Workflow display name
     */
    name: string;
    /**
     * Optional version (defaults to 1.0.0)
     */
    version?: string | null;
};

/**
 * Response returned after successfully deleting a campaign
 */
export type DeleteCampaignResponse = {
    /**
     * Confirmation message
     */
    message: string;
    /**
     * True if deletion succeeded
     */
    success: boolean;
};

/**
 * Response returned after successfully deleting a workflow
 */
export type DeleteWorkflowResponse = {
    /**
     * Confirmation message
     */
    message: string;
    /**
     * True if deletion succeeded
     */
    success: boolean;
};

export type DisplaySettings = {
    margin: number;
    monitor_index: number;
    offset_x: number;
    offset_y: number;
    screen_height: number;
    screen_width: number;
};

/**
 * Request payload to encrypt a secret string
 */
export type EncryptSecretRequest = {
    /**
     * Optional encryption master passphrase (falls back to AUTOMA_PASSPHRASE env)
     */
    passphrase?: string | null;
    /**
     * Plaintext string to encrypt
     */
    plaintext: string;
};

/**
 * Response containing ciphertext secret
 */
export type EncryptSecretResponse = {
    /**
     * Base64 encrypted secret ciphertext
     */
    encryptedSecret: string;
};

/**
 * Request payload to trigger or schedule a campaign execution
 */
export type ExecuteCampaignRequest = {
    /**
     * Optional custom campaign identifier
     */
    campaignId?: string | null;
    /**
     * Path to the `.campaign.json` descriptor file
     */
    campaignPath?: string | null;
    /**
     * Immediately start executing jobs
     */
    runNow?: boolean | null;
    /**
     * Automatically tile browser windows across screen grid
     */
    useGrid?: boolean | null;
};

/**
 * Response returned after scheduling a campaign
 */
export type ExecuteCampaignResponse = {
    /**
     * Grid matrix slot assignments
     */
    allocatedSlots: Array<MatrixSlotInfo>;
    /**
     * Unique campaign identifier
     */
    campaignId: string;
    /**
     * List of created job identifiers
     */
    jobIds: Array<string>;
    /**
     * Current campaign state
     */
    status: string;
    /**
     * Total execution jobs generated
     */
    totalJobs: number;
};

export type GridBehavior = {
    auto_recycle_slots: boolean;
    enforce_cdp_bounds: boolean;
    scale_factor: number;
};

export type GridMatrix = {
    columns: number;
    rows: number;
};

export type GridSettings = {
    behavior: GridBehavior;
    display: DisplaySettings;
    enabled: boolean;
    matrix: GridMatrix;
};

/**
 * Daemon health check response
 */
export type HealthResponse = {
    /**
     * Status message description
     */
    message: string;
    /**
     * Overall operational status ("ok", "degraded")
     */
    status: string;
    /**
     * Semantic version of the running daemon binary
     */
    version: string;
};

/**
 * Response returned after performing a history modification or purge action
 */
export type HistoryActionResponse = {
    /**
     * Detailed status message
     */
    message: string;
    /**
     * Whether the history action succeeded
     */
    success: boolean;
};

/**
 * Request payload for importing a campaign into SQLite database
 */
export type ImportCampaignStorageRequest = {
    /**
     * Raw campaign JSON content
     */
    campaign: {
        [key: string]: unknown;
    };
    /**
     * Optional custom ID
     */
    id?: string | null;
};

/**
 * Request payload containing raw CSV formatted browser profiles
 */
export type ImportCsvPayload = {
    /**
     * Raw CSV string containing profile headers and rows
     */
    csv_string: string;
};

/**
 * Response after batch importing browser profiles from CSV
 */
export type ImportCsvResponse = {
    /**
     * Number of profiles successfully imported
     */
    imported: number;
    /**
     * Result description message
     */
    message: string;
    /**
     * Status code indicator
     */
    status: string;
};

/**
 * Request payload for importing a workflow into SQLite database
 */
export type ImportWorkflowStorageRequest = {
    /**
     * Optional custom ID to assign
     */
    id?: string | null;
    /**
     * Raw workflow JSON content
     */
    workflow: {
        [key: string]: unknown;
    };
};

export type JobDetails = {
    error?: string | null;
    job?: null | JobInfo;
    logs?: Array<unknown> | null;
    results?: unknown;
};

export type JobHistoryItem = {
    createdAt: string;
    id: string;
    name: string;
    status: string;
    updatedAt: string;
};

export type JobInfo = {
    createdAt: string;
    duration?: number | null;
    endedAt: string;
    id: string;
    name: string;
    status: string;
    workflowId: string;
};

/**
 * Payload containing execution logs and telemetry emitted by a workflow step
 */
export type JobLogPayload = {
    /**
     * Array of structured log entries or node execution telemetry
     */
    logs?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Human-readable log message
     */
    message?: string | null;
    /**
     * Log severity level ("info", "warn", "error", "debug")
     */
    type: string;
};

/**
 * Current execution status of a background job
 */
export type JobStatusResponse = {
    /**
     * Status name ("running", "completed", "failed", "cancelled")
     */
    status: string;
};

/**
 * Diagnostic issue report detected by the linter
 */
export type LintIssue = {
    /**
     * Machine-readable rule code for IDE filtering and categorization
     */
    code?: string | null;
    /**
     * Detailed diagnostic explanation
     */
    message: string;
    /**
     * Node ID associated with this diagnostic issue, if applicable
     */
    nodeId?: string | null;
    /**
     * JSONPath location of the affected element
     */
    path?: string | null;
    /**
     * Severity level ("warning", "error", "info")
     */
    severity: LintSeverity;
};

/**
 * Execution context mode for the linter
 */
export type LintMode = 'editor' | 'runner';

/**
 * Request payload to lint workflows, campaigns, browsers, or packages
 */
export type LintRequest = {
    /**
     * Optional raw JSON content or document for auto-detection
     */
    content?: {
        [key: string]: unknown;
    } | null;
    /**
     * Optional entire workflow payload containing nested drawflow
     */
    drawflow?: {
        [key: string]: unknown;
    } | null;
    /**
     * Array of workflow edge connection descriptors
     */
    edges?: Array<{
        [key: string]: unknown;
    }> | null;
    mode?: null | LintMode;
    /**
     * Array of workflow block node definitions
     */
    nodes?: Array<{
        [key: string]: unknown;
    }> | null;
    targetType?: null | LintTargetType;
};

/**
 * Result of static AST and schema validation
 */
export type LintResponse = {
    /**
     * List of detected validation warnings, errors, and info diagnostics
     */
    issues: Array<LintIssue>;
    /**
     * Mode used during evaluation
     */
    mode: LintMode;
    /**
     * Detected asset target type
     */
    targetType: LintTargetType;
    /**
     * Whether the asset passed validation without errors
     */
    valid: boolean;
};

/**
 * Severity level of detected lint diagnostic
 */
export type LintSeverity = 'error' | 'warning' | 'info';

/**
 * Target asset type being validated
 */
export type LintTargetType = 'workflow' | 'campaign' | 'browser' | 'package' | 'auto';

export type LogItem = {
    createdAt: string;
    id: number;
    jobId: string;
    message: string;
    type: string;
};

/**
 * Display bounds and runtime state for a grid window slot
 */
export type MatrixSlotInfo = {
    /**
     * Assigned browser profile ID (if any)
     */
    browserId?: string | null;
    /**
     * Window height in pixels
     */
    height: number;
    /**
     * 0-indexed matrix slot position
     */
    slotIndex: number;
    /**
     * Slot status ("ready", "running", "completed", "failed")
     */
    status: string;
    /**
     * Window width in pixels
     */
    width: number;
    /**
     * Window X coordinate in pixels
     */
    x: number;
    /**
     * Window Y coordinate in pixels
     */
    y: number;
};

/**
 * Grid matrix telemetry and slot allocation for a campaign
 */
export type MatrixStatusResponse = {
    /**
     * Detailed matrix slots currently allocated
     */
    activeSlots: Array<MatrixSlotInfo>;
    /**
     * Unique campaign identifier
     */
    campaignId: string;
    /**
     * Number of completed tasks
     */
    completedTasks: number;
    /**
     * Overall campaign status ("active", "completed", "aborted")
     */
    status: string;
    /**
     * Total tasks queued in the campaign
     */
    totalTasks: number;
};

export type RunnerSettings = {
    auto_clean_history_days: number;
    max_concurrent_jobs: number;
    timeout_ms: number;
};

/**
 * Request payload for saving or updating a workflow file
 */
export type SaveWorkflowPayload = {
    /**
     * Workflow JSON content object (nodes, edges, settings)
     */
    content: {
        [key: string]: unknown;
    };
    /**
     * Target filesystem path where the workflow should be written
     */
    path: string;
};

/**
 * Response returned after saving a workflow file
 */
export type SaveWorkflowResponse = {
    /**
     * Status description message
     */
    message: string;
    /**
     * Whether the file was written successfully
     */
    success: boolean;
};

/**
 * Payload containing filesystem path to an unpacked browser extension
 */
export type SideloadExtensionPayload = {
    /**
     * Full filesystem path to the unpacked extension directory (containing manifest.json)
     */
    extension_path: string;
};

/**
 * Response after sideloading an extension into a browser profile
 */
export type SideloadExtensionResponse = {
    /**
     * Detailed result message
     */
    message: string;
    /**
     * Status code indicator
     */
    status: string;
    /**
     * Whether sideload succeeded
     */
    success: boolean;
};

/**
 * Response payload when a browser process is terminated
 */
export type StopBrowserResponse = {
    /**
     * Detailed message
     */
    message: string;
    /**
     * Result status
     */
    status: string;
};

/**
 * Stored authentication credential
 */
export type StorageCredential = {
    /**
     * Unique credential identifier
     */
    id?: string | null;
    /**
     * Credential lookup key
     */
    key?: string | null;
    /**
     * Display name of the credential
     */
    name?: string | null;
    /**
     * Encrypted or plaintext secret value
     */
    value?: string | null;
};

/**
 * User data table schema in Automa storage
 */
export type StorageTable = {
    /**
     * Array of column definitions
     */
    columns?: {
        [key: string]: unknown;
    } | null;
    /**
     * Index mapping for columns
     */
    columnsIndex?: {
        [key: string]: unknown;
    } | null;
    /**
     * Creation timestamp in milliseconds
     */
    createdAt?: number | null;
    /**
     * Unique table identifier
     */
    id?: string | null;
    /**
     * Optional inline items cache
     */
    items?: {
        [key: string]: unknown;
    } | null;
    /**
     * Last modification timestamp in milliseconds
     */
    modifiedAt?: number | null;
    /**
     * Table display name
     */
    name?: string | null;
};

/**
 * Global variable stored in Automa SQLite / FS storage
 */
export type StorageVariable = {
    /**
     * Unique variable identifier
     */
    id?: string | null;
    /**
     * Unique variable key used in workflow expressions
     */
    key?: string | null;
    /**
     * Human-friendly display label
     */
    name?: string | null;
    /**
     * Arbitrary JSON value or primitive stored
     */
    value: {
        [key: string]: unknown;
    };
};

/**
 * Advanced runtime execution options for a workflow job
 */
export type SubmitJobOptions = {
    /**
     * Target browser instance ID (defaults to "daemon_worker")
     */
    browserId?: string | null;
    /**
     * Automatically close browser session when workflow execution finishes
     */
    closeBrowserOnFinish?: boolean | null;
    /**
     * Enable verbose debugging and DevTools inspection
     */
    debug?: boolean | null;
    /**
     * Browser executable type ("chromium", "chrome", "edge", "firefox")
     */
    defaultBrowser?: string | null;
    /**
     * Run browser in headless mode (no visible window)
     */
    headless?: boolean | null;
    /**
     * Dynamic variables to inject into the workflow execution scope
     */
    variables?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Request payload for submitting a new workflow execution job
 */
export type SubmitJobPayload = {
    options?: null | SubmitJobOptions;
    /**
     * Raw inline workflow JSON payload (alternative to workflowPath or workflowId)
     */
    workflowData?: {
        [key: string]: unknown;
    } | null;
    /**
     * Unique identifier of the workflow to execute
     */
    workflowId?: string | null;
    /**
     * Absolute or relative filesystem path to the `.workflow.json` file (deprecated, prefer workflowId)
     */
    workflowPath?: string | null;
};

/**
 * Response returned after successfully submitting a workflow job
 */
export type SubmitJobResponse = {
    /**
     * Unique identifier of the created execution job
     */
    jobId: string;
    /**
     * Optional status or error message
     */
    message?: string | null;
    /**
     * Initial lifecycle status (e.g. "queued", "running")
     */
    status: string;
};

/**
 * Real-time CPU, RAM, and browser runner metrics
 */
export type SystemMetricsResponse = {
    /**
     * Number of actively connected browser runner instances
     */
    activeRunners: number;
    /**
     * Global CPU utilization percentage (0 - 100)
     */
    cpuUsage: number;
    /**
     * Free system memory in bytes
     */
    memoryFree: number;
    /**
     * Total system physical memory in bytes
     */
    memoryTotal: number;
};

/**
 * General system action response
 */
export type SystemResponse = {
    /**
     * Result description message
     */
    message: string;
    /**
     * Whether the system operation succeeded
     */
    success: boolean;
};

/**
 * Single data row entry belonging to a storage table
 */
export type TableRow = {
    /**
     * Key-value document payload of row columns
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Unique row identifier
     */
    id: string;
    /**
     * Parent table identifier
     */
    table_id: string;
};

export type UpdateAppSettingsRequest = {
    browser?: null | UpdateBrowserSettingsRequest;
    grid?: null | UpdateGridSettingsRequest;
    runner?: null | UpdateRunnerSettingsRequest;
};

/**
 * Request payload for modifying an existing browser profile
 */
export type UpdateBrowserRequest = {
    /**
     * New profile display name
     */
    name?: string | null;
    /**
     * New emulated timezone ID
     */
    timezone?: string | null;
    /**
     * New custom User-Agent
     */
    userAgent?: string | null;
};

export type UpdateBrowserSettingsRequest = {
    default_profile_id?: string | null;
    default_type?: string | null;
    default_user_agent?: string | null;
    executable_path?: string | null;
    headless?: boolean | null;
};

/**
 * Request payload for updating an existing campaign in SQLite database
 */
export type UpdateCampaignStorageRequest = {
    /**
     * Optional updated cron expression
     */
    cron?: string | null;
    /**
     * Optional updated campaign data
     */
    data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Optional updated description
     */
    description?: string | null;
    /**
     * Optional updated name
     */
    name?: string | null;
    /**
     * Optional updated version
     */
    version?: string | null;
};

export type UpdateDisplaySettingsRequest = {
    margin?: number | null;
    monitor_index?: number | null;
    offset_x?: number | null;
    offset_y?: number | null;
    screen_height?: number | null;
    screen_width?: number | null;
};

export type UpdateGridBehaviorRequest = {
    auto_recycle_slots?: boolean | null;
    enforce_cdp_bounds?: boolean | null;
    scale_factor?: number | null;
};

export type UpdateGridMatrixRequest = {
    columns?: number | null;
    rows?: number | null;
};

export type UpdateGridSettingsRequest = {
    behavior?: null | UpdateGridBehaviorRequest;
    display?: null | UpdateDisplaySettingsRequest;
    enabled?: boolean | null;
    matrix?: null | UpdateGridMatrixRequest;
};

export type UpdateRunnerSettingsRequest = {
    auto_clean_history_days?: number | null;
    max_concurrent_jobs?: number | null;
    timeout_ms?: number | null;
};

/**
 * Request payload for updating an existing workflow in SQLite database
 */
export type UpdateWorkflowStorageRequest = {
    /**
     * Optional updated workflow graph AST
     */
    data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Optional updated description
     */
    description?: string | null;
    /**
     * Optional updated icon
     */
    icon?: string | null;
    /**
     * Optional updated name
     */
    name?: string | null;
    /**
     * Optional updated version
     */
    version?: string | null;
};

/**
 * Workflow descriptor stored in central SQLite database
 */
export type WorkflowStorageItem = {
    /**
     * Creation timestamp (ISO 8601)
     */
    createdAt: string;
    /**
     * Workflow graph AST (nodes, edges, settings)
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Optional workflow description
     */
    description?: string | null;
    /**
     * Optional UI icon identifier
     */
    icon?: string | null;
    /**
     * Unique workflow identifier
     */
    id: string;
    /**
     * Workflow display name
     */
    name: string;
    /**
     * Last modification timestamp (ISO 8601)
     */
    updatedAt: string;
    /**
     * Semantic version of the workflow
     */
    version: string;
};

export type GetBrowsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of browser profiles to return
         */
        limit?: number | null;
        /**
         * Number of items to skip for pagination (default 0)
         */
        offset?: number | null;
        /**
         * Optional search query to filter browsers by name or ID
         */
        search?: string | null;
    };
    url: '/api/v1/browsers';
};

export type GetBrowsersErrors = {
    /**
     * Database read error
     */
    500: ApiErrorResponse;
};

export type GetBrowsersError = GetBrowsersErrors[keyof GetBrowsersErrors];

export type GetBrowsersResponses = {
    /**
     * List of all browser profiles
     */
    200: Array<BrowserResponse>;
};

export type GetBrowsersResponse = GetBrowsersResponses[keyof GetBrowsersResponses];

export type CreateBrowserData = {
    body: CreateBrowserRequest;
    path?: never;
    query?: never;
    url: '/api/v1/browsers';
};

export type CreateBrowserErrors = {
    /**
     * Invalid browser ID or missing name
     */
    400: ApiErrorResponse;
    /**
     * Failed to create browser profile in database
     */
    500: ApiErrorResponse;
};

export type CreateBrowserError = CreateBrowserErrors[keyof CreateBrowserErrors];

export type CreateBrowserResponses = {
    /**
     * Browser profile created successfully
     */
    200: unknown;
};

export type AutoDetectBrowsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/browsers/auto-detect';
};

export type AutoDetectBrowsersErrors = {
    /**
     * Database error during auto-detection
     */
    500: ApiErrorResponse;
};

export type AutoDetectBrowsersError = AutoDetectBrowsersErrors[keyof AutoDetectBrowsersErrors];

export type AutoDetectBrowsersResponses = {
    /**
     * List of all registered browser profiles after detection
     */
    200: Array<BrowserResponse>;
};

export type AutoDetectBrowsersResponse = AutoDetectBrowsersResponses[keyof AutoDetectBrowsersResponses];

export type ImportBrowsersCsvData = {
    body: ImportCsvPayload;
    path?: never;
    query?: never;
    url: '/api/v1/browsers/import-csv';
};

export type ImportBrowsersCsvErrors = {
    /**
     * Malformed CSV format
     */
    400: ApiErrorResponse;
};

export type ImportBrowsersCsvError = ImportBrowsersCsvErrors[keyof ImportBrowsersCsvErrors];

export type ImportBrowsersCsvResponses = {
    /**
     * CSV profiles successfully parsed and imported
     */
    200: ImportCsvResponse;
};

export type ImportBrowsersCsvResponse = ImportBrowsersCsvResponses[keyof ImportBrowsersCsvResponses];

export type KillAllBrowsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/browsers/sessions';
};

export type KillAllBrowsersResponses = {
    /**
     * All managed browser processes terminated
     */
    200: SystemResponse;
};

export type KillAllBrowsersResponse = KillAllBrowsersResponses[keyof KillAllBrowsersResponses];

export type DeleteBrowserData = {
    body?: never;
    path: {
        /**
         * Unique browser profile identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/browsers/{id}';
};

export type DeleteBrowserErrors = {
    /**
     * Invalid browser ID
     */
    400: ApiErrorResponse;
    /**
     * Browser profile not found
     */
    404: ApiErrorResponse;
    /**
     * Database deletion error
     */
    500: ApiErrorResponse;
};

export type DeleteBrowserError = DeleteBrowserErrors[keyof DeleteBrowserErrors];

export type DeleteBrowserResponses = {
    /**
     * Browser profile deleted successfully
     */
    200: unknown;
};

export type GetBrowserDetailData = {
    body?: never;
    path: {
        /**
         * Unique browser profile identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/browsers/{id}';
};

export type GetBrowserDetailErrors = {
    /**
     * Invalid browser ID
     */
    400: ApiErrorResponse;
    /**
     * Browser profile not found
     */
    404: ApiErrorResponse;
    /**
     * Database query error
     */
    500: ApiErrorResponse;
};

export type GetBrowserDetailError = GetBrowserDetailErrors[keyof GetBrowserDetailErrors];

export type GetBrowserDetailResponses = {
    /**
     * Browser profile details
     */
    200: BrowserResponse;
};

export type GetBrowserDetailResponse = GetBrowserDetailResponses[keyof GetBrowserDetailResponses];

export type UpdateBrowserData = {
    body: UpdateBrowserRequest;
    path: {
        /**
         * Unique browser profile identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/browsers/{id}';
};

export type UpdateBrowserErrors = {
    /**
     * Invalid browser ID
     */
    400: ApiErrorResponse;
    /**
     * Browser profile not found
     */
    404: ApiErrorResponse;
    /**
     * Database update error
     */
    500: ApiErrorResponse;
};

export type UpdateBrowserError = UpdateBrowserErrors[keyof UpdateBrowserErrors];

export type UpdateBrowserResponses = {
    /**
     * Browser profile updated successfully
     */
    200: unknown;
};

export type GetBrowserCookiesData = {
    body?: never;
    path: {
        /**
         * Unique browser profile identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/browsers/{id}/cookies';
};

export type GetBrowserCookiesErrors = {
    /**
     * Browser profile not found
     */
    404: ApiErrorResponse;
    /**
     * Failed to access or decrypt cookie store
     */
    500: ApiErrorResponse;
};

export type GetBrowserCookiesError = GetBrowserCookiesErrors[keyof GetBrowserCookiesErrors];

export type GetBrowserCookiesResponses = {
    /**
     * Decrypted array of cookies
     */
    200: Array<Cookie>;
};

export type GetBrowserCookiesResponse = GetBrowserCookiesResponses[keyof GetBrowserCookiesResponses];

export type ImportBrowserCookiesData = {
    body: Array<Cookie>;
    path: {
        /**
         * Unique browser profile identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/browsers/{id}/cookies';
};

export type ImportBrowserCookiesErrors = {
    /**
     * Malformed cookie data
     */
    400: ApiErrorResponse;
    /**
     * Failed to write cookies to database
     */
    500: ApiErrorResponse;
};

export type ImportBrowserCookiesError = ImportBrowserCookiesErrors[keyof ImportBrowserCookiesErrors];

export type ImportBrowserCookiesResponses = {
    /**
     * Cookies successfully imported
     */
    200: unknown;
};

export type SideloadBrowserExtensionData = {
    body: SideloadExtensionPayload;
    path: {
        /**
         * Unique browser profile identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/browsers/{id}/extensions';
};

export type SideloadBrowserExtensionErrors = {
    /**
     * Invalid extension path or manifest
     */
    400: ApiErrorResponse;
    /**
     * Browser profile not found
     */
    404: ApiErrorResponse;
};

export type SideloadBrowserExtensionError = SideloadBrowserExtensionErrors[keyof SideloadBrowserExtensionErrors];

export type SideloadBrowserExtensionResponses = {
    /**
     * Extension sideloaded successfully
     */
    200: SideloadExtensionResponse;
};

export type SideloadBrowserExtensionResponse = SideloadBrowserExtensionResponses[keyof SideloadBrowserExtensionResponses];

export type StopBrowserSessionData = {
    body?: never;
    path: {
        /**
         * Unique browser profile identifier
         */
        id: string;
    };
    query?: {
        /**
         * If true, forcefully kills the process immediately without graceful closing or saving cache
         */
        force?: boolean | null;
    };
    url: '/api/v1/browsers/{id}/session';
};

export type StopBrowserSessionErrors = {
    /**
     * Invalid browser ID
     */
    400: ApiErrorResponse;
};

export type StopBrowserSessionError = StopBrowserSessionErrors[keyof StopBrowserSessionErrors];

export type StopBrowserSessionResponses = {
    /**
     * Browser session terminated successfully
     */
    200: StopBrowserResponse;
};

export type StopBrowserSessionResponse = StopBrowserSessionResponses[keyof StopBrowserSessionResponses];

export type StartBrowserData = {
    body?: never;
    path: {
        /**
         * Unique browser profile identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/browsers/{id}/session';
};

export type StartBrowserErrors = {
    /**
     * Invalid browser ID or configuration error
     */
    400: ApiErrorResponse;
    /**
     * Process spawn failure
     */
    500: ApiErrorResponse;
};

export type StartBrowserError = StartBrowserErrors[keyof StartBrowserErrors];

export type StartBrowserResponses = {
    /**
     * Browser session started
     */
    200: unknown;
};

export type ExecuteCampaignData = {
    body: ExecuteCampaignRequest;
    path?: never;
    query?: never;
    url: '/api/v1/campaigns/execute';
};

export type ExecuteCampaignErrors = {
    /**
     * Invalid campaign payload or unreadable descriptor
     */
    400: ApiErrorResponse;
};

export type ExecuteCampaignError = ExecuteCampaignErrors[keyof ExecuteCampaignErrors];

export type ExecuteCampaignResponses = {
    /**
     * Campaign execution scheduled
     */
    200: ExecuteCampaignResponse;
};

export type ExecuteCampaignResponse2 = ExecuteCampaignResponses[keyof ExecuteCampaignResponses];

export type AbortCampaignData = {
    body?: never;
    path: {
        /**
         * Unique campaign identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/campaigns/{id}';
};

export type AbortCampaignErrors = {
    /**
     * Campaign not found
     */
    404: ApiErrorResponse;
};

export type AbortCampaignError = AbortCampaignErrors[keyof AbortCampaignErrors];

export type AbortCampaignResponses = {
    /**
     * Campaign aborted successfully
     */
    200: unknown;
};

export type GetCampaignMatrixStatusData = {
    body?: never;
    path: {
        /**
         * Unique campaign identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/campaigns/{id}/matrix-status';
};

export type GetCampaignMatrixStatusErrors = {
    /**
     * Campaign not found
     */
    404: ApiErrorResponse;
};

export type GetCampaignMatrixStatusError = GetCampaignMatrixStatusErrors[keyof GetCampaignMatrixStatusErrors];

export type GetCampaignMatrixStatusResponses = {
    /**
     * Matrix status and slot allocation
     */
    200: MatrixStatusResponse;
};

export type GetCampaignMatrixStatusResponse = GetCampaignMatrixStatusResponses[keyof GetCampaignMatrixStatusResponses];

export type SubscribeEventsSseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type SubscribeEventsSseResponses = {
    /**
     * Server-Sent Events stream for task logs and progress
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetHealthResponses = {
    /**
     * Daemon is healthy and accepting requests
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ClearAllJobHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/history';
};

export type ClearAllJobHistoryErrors = {
    /**
     * Database purge failure
     */
    500: ApiErrorResponse;
};

export type ClearAllJobHistoryError = ClearAllJobHistoryErrors[keyof ClearAllJobHistoryErrors];

export type ClearAllJobHistoryResponses = {
    /**
     * All job history cleared successfully
     */
    200: HistoryActionResponse;
};

export type ClearAllJobHistoryResponse = ClearAllJobHistoryResponses[keyof ClearAllJobHistoryResponses];

export type GetJobHistoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of history entries to return (default 50)
         */
        limit?: number | null;
        /**
         * Number of items to skip for pagination (default 0)
         */
        offset?: number | null;
        /**
         * Optional search query to filter history by workflow name or job ID
         */
        search?: string | null;
        /**
         * Optional status filter (e.g. "completed", "failed", "running")
         */
        status?: string | null;
    };
    url: '/api/v1/history';
};

export type GetJobHistoryErrors = {
    /**
     * Database or thread pool failure
     */
    500: ApiErrorResponse;
};

export type GetJobHistoryError = GetJobHistoryErrors[keyof GetJobHistoryErrors];

export type GetJobHistoryResponses = {
    /**
     * List of past job execution summaries
     */
    200: Array<JobHistoryItem>;
};

export type GetJobHistoryResponse = GetJobHistoryResponses[keyof GetJobHistoryResponses];

export type DeleteJobHistoryItemData = {
    body?: never;
    path: {
        /**
         * Unique job identifier to delete
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/history/{job_id}';
};

export type DeleteJobHistoryItemErrors = {
    /**
     * Job not found
     */
    404: ApiErrorResponse;
    /**
     * Database deletion failure
     */
    500: ApiErrorResponse;
};

export type DeleteJobHistoryItemError = DeleteJobHistoryItemErrors[keyof DeleteJobHistoryItemErrors];

export type DeleteJobHistoryItemResponses = {
    /**
     * Job history entry deleted successfully
     */
    200: HistoryActionResponse;
};

export type DeleteJobHistoryItemResponse = DeleteJobHistoryItemResponses[keyof DeleteJobHistoryItemResponses];

export type GetJobExecutionLogsData = {
    body?: never;
    path: {
        /**
         * Unique job identifier
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/history/{job_id}/logs';
};

export type GetJobExecutionLogsErrors = {
    /**
     * Job not found
     */
    404: ApiErrorResponse;
    /**
     * Database query failure
     */
    500: ApiErrorResponse;
};

export type GetJobExecutionLogsError = GetJobExecutionLogsErrors[keyof GetJobExecutionLogsErrors];

export type GetJobExecutionLogsResponses = {
    /**
     * Detailed job execution record and logs
     */
    200: JobDetails;
};

export type GetJobExecutionLogsResponse = GetJobExecutionLogsResponses[keyof GetJobExecutionLogsResponses];

export type WorkerSseData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Target browser instance identifier (defaults to 'daemon_worker')
         */
        browserId?: string;
    };
    url: '/api/v1/internal/worker/events';
};

export type WorkerSseResponses = {
    /**
     * SSE Stream for Worker jobs
     */
    200: unknown;
};

export type GetActiveJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of active jobs to return
         */
        limit?: number | null;
        /**
         * Number of items to skip for pagination (default 0)
         */
        offset?: number | null;
        /**
         * Optional search query to filter active jobs by job ID
         */
        search?: string | null;
    };
    url: '/api/v1/jobs';
};

export type GetActiveJobsResponses = {
    /**
     * List of active running jobs
     */
    200: Array<ActiveJobResponse>;
};

export type GetActiveJobsResponse = GetActiveJobsResponses[keyof GetActiveJobsResponses];

export type SubmitJobData = {
    body: SubmitJobPayload;
    path?: never;
    query?: never;
    url: '/api/v1/jobs';
};

export type SubmitJobErrors = {
    /**
     * Invalid request payload or unreadable workflow file
     */
    400: ApiErrorResponse;
    /**
     * Maximum concurrent jobs reached
     */
    429: SubmitJobResponse;
    /**
     * Browser worker unavailable or connection timeout
     */
    503: SubmitJobResponse;
};

export type SubmitJobError = SubmitJobErrors[keyof SubmitJobErrors];

export type SubmitJobResponses = {
    /**
     * Job submitted and accepted for execution
     */
    200: SubmitJobResponse;
};

export type SubmitJobResponse2 = SubmitJobResponses[keyof SubmitJobResponses];

export type KillJobData = {
    body?: never;
    path: {
        /**
         * Unique job identifier
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}';
};

export type KillJobErrors = {
    /**
     * Job not found or not active
     */
    404: ApiErrorResponse;
};

export type KillJobError = KillJobErrors[keyof KillJobErrors];

export type KillJobResponses = {
    /**
     * Job aborted successfully
     */
    200: unknown;
};

export type AppendJobLogData = {
    body: JobLogPayload;
    path: {
        /**
         * Unique job identifier
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}/logs';
};

export type AppendJobLogErrors = {
    /**
     * Invalid payload or job not found
     */
    400: ApiErrorResponse;
};

export type AppendJobLogError = AppendJobLogErrors[keyof AppendJobLogErrors];

export type AppendJobLogResponses = {
    /**
     * Log entry received and persisted successfully
     */
    200: unknown;
};

export type GetJobStatusData = {
    body?: never;
    path: {
        /**
         * Unique job identifier
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}/status';
};

export type GetJobStatusErrors = {
    /**
     * Job not found
     */
    404: ApiErrorResponse;
};

export type GetJobStatusError = GetJobStatusErrors[keyof GetJobStatusErrors];

export type GetJobStatusResponses = {
    /**
     * Current job execution status
     */
    200: JobStatusResponse;
};

export type GetJobStatusResponse = GetJobStatusResponses[keyof GetJobStatusResponses];

export type FinishJobData = {
    body?: never;
    path: {
        /**
         * Unique job identifier
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}/status';
};

export type FinishJobErrors = {
    /**
     * Job not found or already finished
     */
    404: ApiErrorResponse;
};

export type FinishJobError = FinishJobErrors[keyof FinishJobErrors];

export type FinishJobResponses = {
    /**
     * Job marked as completed successfully
     */
    200: unknown;
};

export type LintWorkflowData = {
    body: LintRequest;
    path?: never;
    query?: never;
    url: '/api/v1/lint';
};

export type LintWorkflowResponses = {
    /**
     * Lint diagnostic results
     */
    200: LintResponse;
};

export type LintWorkflowResponse = LintWorkflowResponses[keyof LintWorkflowResponses];

export type EncryptSecretData = {
    body: EncryptSecretRequest;
    path?: never;
    query?: never;
    url: '/api/v1/secrets/encrypt';
};

export type EncryptSecretErrors = {
    /**
     * Missing plaintext or passphrase
     */
    400: ApiErrorResponse;
    /**
     * Internal encryption failure
     */
    500: ApiErrorResponse;
};

export type EncryptSecretError = EncryptSecretErrors[keyof EncryptSecretErrors];

export type EncryptSecretResponses = {
    /**
     * Secret encrypted successfully
     */
    200: EncryptSecretResponse;
};

export type EncryptSecretResponse2 = EncryptSecretResponses[keyof EncryptSecretResponses];

export type GetStorageCampaignsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of campaigns to return
         */
        limit?: number | null;
        /**
         * Number of items to skip for pagination (default 0)
         */
        offset?: number | null;
        /**
         * Optional search query to filter campaigns by name, ID or description
         */
        search?: string | null;
    };
    url: '/api/v1/storage/campaigns';
};

export type GetStorageCampaignsErrors = {
    /**
     * Database read error
     */
    500: ApiErrorResponse;
};

export type GetStorageCampaignsError = GetStorageCampaignsErrors[keyof GetStorageCampaignsErrors];

export type GetStorageCampaignsResponses = {
    /**
     * List of campaigns
     */
    200: Array<CampaignStorageItem>;
};

export type GetStorageCampaignsResponse = GetStorageCampaignsResponses[keyof GetStorageCampaignsResponses];

export type CreateStorageCampaignData = {
    body: CreateCampaignStorageRequest;
    path?: never;
    query?: never;
    url: '/api/v1/storage/campaigns';
};

export type CreateStorageCampaignErrors = {
    /**
     * Invalid campaign payload
     */
    400: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type CreateStorageCampaignError = CreateStorageCampaignErrors[keyof CreateStorageCampaignErrors];

export type CreateStorageCampaignResponses = {
    /**
     * Campaign created successfully
     */
    200: CampaignStorageItem;
};

export type CreateStorageCampaignResponse = CreateStorageCampaignResponses[keyof CreateStorageCampaignResponses];

export type ImportStorageCampaignData = {
    body: ImportCampaignStorageRequest;
    path?: never;
    query?: never;
    url: '/api/v1/storage/campaigns/import';
};

export type ImportStorageCampaignErrors = {
    /**
     * Invalid campaign JSON
     */
    400: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type ImportStorageCampaignError = ImportStorageCampaignErrors[keyof ImportStorageCampaignErrors];

export type ImportStorageCampaignResponses = {
    /**
     * Campaign imported successfully
     */
    200: CampaignStorageItem;
};

export type ImportStorageCampaignResponse = ImportStorageCampaignResponses[keyof ImportStorageCampaignResponses];

export type DeleteStorageCampaignData = {
    body?: never;
    path: {
        /**
         * Unique campaign identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/campaigns/{id}';
};

export type DeleteStorageCampaignErrors = {
    /**
     * Campaign not found
     */
    404: ApiErrorResponse;
    /**
     * Database deletion error
     */
    500: ApiErrorResponse;
};

export type DeleteStorageCampaignError = DeleteStorageCampaignErrors[keyof DeleteStorageCampaignErrors];

export type DeleteStorageCampaignResponses = {
    /**
     * Campaign deleted successfully
     */
    200: DeleteCampaignResponse;
};

export type DeleteStorageCampaignResponse = DeleteStorageCampaignResponses[keyof DeleteStorageCampaignResponses];

export type GetStorageCampaignData = {
    body?: never;
    path: {
        /**
         * Unique campaign identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/campaigns/{id}';
};

export type GetStorageCampaignErrors = {
    /**
     * Campaign not found
     */
    404: ApiErrorResponse;
    /**
     * Database read error
     */
    500: ApiErrorResponse;
};

export type GetStorageCampaignError = GetStorageCampaignErrors[keyof GetStorageCampaignErrors];

export type GetStorageCampaignResponses = {
    /**
     * Campaign details
     */
    200: CampaignStorageItem;
};

export type GetStorageCampaignResponse = GetStorageCampaignResponses[keyof GetStorageCampaignResponses];

export type UpdateStorageCampaignData = {
    body: UpdateCampaignStorageRequest;
    path: {
        /**
         * Unique campaign identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/campaigns/{id}';
};

export type UpdateStorageCampaignErrors = {
    /**
     * Invalid update payload
     */
    400: ApiErrorResponse;
    /**
     * Campaign not found
     */
    404: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type UpdateStorageCampaignError = UpdateStorageCampaignErrors[keyof UpdateStorageCampaignErrors];

export type UpdateStorageCampaignResponses = {
    /**
     * Campaign updated successfully
     */
    200: CampaignStorageItem;
};

export type UpdateStorageCampaignResponse = UpdateStorageCampaignResponses[keyof UpdateStorageCampaignResponses];

export type GetStorageCredentialsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of credentials to return
         */
        limit?: number | null;
        /**
         * Number of items to skip for pagination (default 0)
         */
        offset?: number | null;
        /**
         * Optional search query to filter credentials by name, key or ID
         */
        search?: string | null;
    };
    url: '/api/v1/storage/credentials';
};

export type GetStorageCredentialsErrors = {
    /**
     * Database read error
     */
    500: ApiErrorResponse;
};

export type GetStorageCredentialsError = GetStorageCredentialsErrors[keyof GetStorageCredentialsErrors];

export type GetStorageCredentialsResponses = {
    /**
     * List of credentials
     */
    200: Array<StorageCredential>;
};

export type GetStorageCredentialsResponse = GetStorageCredentialsResponses[keyof GetStorageCredentialsResponses];

export type AddStorageCredentialData = {
    body: StorageCredential;
    path?: never;
    query?: never;
    url: '/api/v1/storage/credentials';
};

export type AddStorageCredentialErrors = {
    /**
     * Invalid credential payload
     */
    400: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type AddStorageCredentialError = AddStorageCredentialErrors[keyof AddStorageCredentialErrors];

export type AddStorageCredentialResponses = {
    /**
     * Credential saved successfully
     */
    200: StorageCredential;
};

export type AddStorageCredentialResponse = AddStorageCredentialResponses[keyof AddStorageCredentialResponses];

export type DeleteStorageCredentialData = {
    body?: never;
    path: {
        /**
         * Credential ID or unique key
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/credentials/{id}';
};

export type DeleteStorageCredentialErrors = {
    /**
     * Credential not found
     */
    404: ApiErrorResponse;
    /**
     * Database deletion error
     */
    500: ApiErrorResponse;
};

export type DeleteStorageCredentialError = DeleteStorageCredentialErrors[keyof DeleteStorageCredentialErrors];

export type DeleteStorageCredentialResponses = {
    /**
     * Credential deleted successfully
     */
    200: unknown;
};

export type GetStorageTablesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of tables to return
         */
        limit?: number | null;
        /**
         * Number of items to skip for pagination (default 0)
         */
        offset?: number | null;
        /**
         * Optional search query to filter tables by name or ID
         */
        search?: string | null;
    };
    url: '/api/v1/storage/tables';
};

export type GetStorageTablesErrors = {
    /**
     * Database read error
     */
    500: ApiErrorResponse;
};

export type GetStorageTablesError = GetStorageTablesErrors[keyof GetStorageTablesErrors];

export type GetStorageTablesResponses = {
    /**
     * List of data tables
     */
    200: Array<StorageTable>;
};

export type GetStorageTablesResponse = GetStorageTablesResponses[keyof GetStorageTablesResponses];

export type AddStorageTableData = {
    body: StorageTable;
    path?: never;
    query?: never;
    url: '/api/v1/storage/tables';
};

export type AddStorageTableErrors = {
    /**
     * Invalid table schema
     */
    400: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type AddStorageTableError = AddStorageTableErrors[keyof AddStorageTableErrors];

export type AddStorageTableResponses = {
    /**
     * Table schema created or updated
     */
    200: StorageTable;
};

export type AddStorageTableResponse = AddStorageTableResponses[keyof AddStorageTableResponses];

export type DeleteStorageTableData = {
    body?: never;
    path: {
        /**
         * Unique table identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/tables/{id}';
};

export type DeleteStorageTableErrors = {
    /**
     * Table not found
     */
    404: ApiErrorResponse;
    /**
     * Database deletion error
     */
    500: ApiErrorResponse;
};

export type DeleteStorageTableError = DeleteStorageTableErrors[keyof DeleteStorageTableErrors];

export type DeleteStorageTableResponses = {
    /**
     * Table and rows deleted successfully
     */
    200: unknown;
};

export type GetStorageTableRowsData = {
    body?: never;
    path: {
        /**
         * Unique table identifier
         */
        id: string;
    };
    query?: {
        /**
         * Maximum number of rows to return (default 50)
         */
        limit?: number | null;
        /**
         * Number of items to skip for pagination (default 0)
         */
        offset?: number | null;
        /**
         * Optional search query to filter rows by data content
         */
        search?: string | null;
    };
    url: '/api/v1/storage/tables/{id}/rows';
};

export type GetStorageTableRowsErrors = {
    /**
     * Table not found
     */
    404: ApiErrorResponse;
    /**
     * Database query error
     */
    500: ApiErrorResponse;
};

export type GetStorageTableRowsError = GetStorageTableRowsErrors[keyof GetStorageTableRowsErrors];

export type GetStorageTableRowsResponses = {
    /**
     * Array of table row objects
     */
    200: Array<TableRow>;
};

export type GetStorageTableRowsResponse = GetStorageTableRowsResponses[keyof GetStorageTableRowsResponses];

export type AddStorageTableRowData = {
    body: AddTableRowPayload;
    path: {
        /**
         * Unique table identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/tables/{id}/rows';
};

export type AddStorageTableRowErrors = {
    /**
     * Malformed row data
     */
    400: ApiErrorResponse;
    /**
     * Table not found
     */
    404: ApiErrorResponse;
    /**
     * Database insertion error
     */
    500: ApiErrorResponse;
};

export type AddStorageTableRowError = AddStorageTableRowErrors[keyof AddStorageTableRowErrors];

export type AddStorageTableRowResponses = {
    /**
     * Row inserted successfully
     */
    200: AddTableRowResponse;
};

export type AddStorageTableRowResponse = AddStorageTableRowResponses[keyof AddStorageTableRowResponses];

export type GetStorageVariablesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of variables to return
         */
        limit?: number | null;
        /**
         * Number of items to skip for pagination (default 0)
         */
        offset?: number | null;
        /**
         * Optional search query to filter variables by name, key or ID
         */
        search?: string | null;
    };
    url: '/api/v1/storage/variables';
};

export type GetStorageVariablesErrors = {
    /**
     * Database read error
     */
    500: ApiErrorResponse;
};

export type GetStorageVariablesError = GetStorageVariablesErrors[keyof GetStorageVariablesErrors];

export type GetStorageVariablesResponses = {
    /**
     * List of variables
     */
    200: Array<StorageVariable>;
};

export type GetStorageVariablesResponse = GetStorageVariablesResponses[keyof GetStorageVariablesResponses];

export type AddStorageVariableData = {
    body: StorageVariable;
    path?: never;
    query?: never;
    url: '/api/v1/storage/variables';
};

export type AddStorageVariableErrors = {
    /**
     * Invalid variable payload
     */
    400: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type AddStorageVariableError = AddStorageVariableErrors[keyof AddStorageVariableErrors];

export type AddStorageVariableResponses = {
    /**
     * Variable saved successfully
     */
    200: StorageVariable;
};

export type AddStorageVariableResponse = AddStorageVariableResponses[keyof AddStorageVariableResponses];

export type DeleteStorageVariableData = {
    body?: never;
    path: {
        /**
         * Variable ID or unique key
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/variables/{id}';
};

export type DeleteStorageVariableErrors = {
    /**
     * Variable not found
     */
    404: ApiErrorResponse;
    /**
     * Database deletion error
     */
    500: ApiErrorResponse;
};

export type DeleteStorageVariableError = DeleteStorageVariableErrors[keyof DeleteStorageVariableErrors];

export type DeleteStorageVariableResponses = {
    /**
     * Variable deleted successfully
     */
    200: unknown;
};

export type GetWorkflowData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Full filesystem path or relative workspace path to the target .workflow.json file
         */
        path: string;
    };
    url: '/api/v1/storage/workflow';
};

export type GetWorkflowErrors = {
    /**
     * Invalid path or unreadable workflow JSON
     */
    400: ApiErrorResponse;
    /**
     * Workflow file not found on disk
     */
    404: ApiErrorResponse;
};

export type GetWorkflowError = GetWorkflowErrors[keyof GetWorkflowErrors];

export type GetWorkflowResponses = {
    /**
     * Workflow JSON file read successfully
     */
    200: unknown;
};

export type SaveWorkflowData = {
    body: SaveWorkflowPayload;
    path?: never;
    query?: never;
    url: '/api/v1/storage/workflow';
};

export type SaveWorkflowErrors = {
    /**
     * Invalid payload or unwriteable path
     */
    400: ApiErrorResponse;
};

export type SaveWorkflowError = SaveWorkflowErrors[keyof SaveWorkflowErrors];

export type SaveWorkflowResponses = {
    /**
     * Workflow JSON file saved successfully
     */
    200: SaveWorkflowResponse;
};

export type SaveWorkflowResponse2 = SaveWorkflowResponses[keyof SaveWorkflowResponses];

export type GetStorageWorkflowsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of workflows to return
         */
        limit?: number | null;
        /**
         * Number of items to skip for pagination (default 0)
         */
        offset?: number | null;
        /**
         * Optional search query to filter workflows by name, ID or description
         */
        search?: string | null;
    };
    url: '/api/v1/storage/workflows';
};

export type GetStorageWorkflowsErrors = {
    /**
     * Database read error
     */
    500: ApiErrorResponse;
};

export type GetStorageWorkflowsError = GetStorageWorkflowsErrors[keyof GetStorageWorkflowsErrors];

export type GetStorageWorkflowsResponses = {
    /**
     * List of workflows
     */
    200: Array<WorkflowStorageItem>;
};

export type GetStorageWorkflowsResponse = GetStorageWorkflowsResponses[keyof GetStorageWorkflowsResponses];

export type CreateStorageWorkflowData = {
    body: CreateWorkflowStorageRequest;
    path?: never;
    query?: never;
    url: '/api/v1/storage/workflows';
};

export type CreateStorageWorkflowErrors = {
    /**
     * Invalid workflow payload
     */
    400: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type CreateStorageWorkflowError = CreateStorageWorkflowErrors[keyof CreateStorageWorkflowErrors];

export type CreateStorageWorkflowResponses = {
    /**
     * Workflow created successfully
     */
    200: WorkflowStorageItem;
};

export type CreateStorageWorkflowResponse = CreateStorageWorkflowResponses[keyof CreateStorageWorkflowResponses];

export type ImportStorageWorkflowData = {
    body: ImportWorkflowStorageRequest;
    path?: never;
    query?: never;
    url: '/api/v1/storage/workflows/import';
};

export type ImportStorageWorkflowErrors = {
    /**
     * Invalid workflow JSON
     */
    400: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type ImportStorageWorkflowError = ImportStorageWorkflowErrors[keyof ImportStorageWorkflowErrors];

export type ImportStorageWorkflowResponses = {
    /**
     * Workflow imported successfully
     */
    200: WorkflowStorageItem;
};

export type ImportStorageWorkflowResponse = ImportStorageWorkflowResponses[keyof ImportStorageWorkflowResponses];

export type DeleteStorageWorkflowData = {
    body?: never;
    path: {
        /**
         * Unique workflow identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/workflows/{id}';
};

export type DeleteStorageWorkflowErrors = {
    /**
     * Workflow not found
     */
    404: ApiErrorResponse;
    /**
     * Database deletion error
     */
    500: ApiErrorResponse;
};

export type DeleteStorageWorkflowError = DeleteStorageWorkflowErrors[keyof DeleteStorageWorkflowErrors];

export type DeleteStorageWorkflowResponses = {
    /**
     * Workflow deleted successfully
     */
    200: DeleteWorkflowResponse;
};

export type DeleteStorageWorkflowResponse = DeleteStorageWorkflowResponses[keyof DeleteStorageWorkflowResponses];

export type GetStorageWorkflowData = {
    body?: never;
    path: {
        /**
         * Unique workflow identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/workflows/{id}';
};

export type GetStorageWorkflowErrors = {
    /**
     * Workflow not found
     */
    404: ApiErrorResponse;
    /**
     * Database read error
     */
    500: ApiErrorResponse;
};

export type GetStorageWorkflowError = GetStorageWorkflowErrors[keyof GetStorageWorkflowErrors];

export type GetStorageWorkflowResponses = {
    /**
     * Workflow details
     */
    200: WorkflowStorageItem;
};

export type GetStorageWorkflowResponse = GetStorageWorkflowResponses[keyof GetStorageWorkflowResponses];

export type UpdateStorageWorkflowData = {
    body: UpdateWorkflowStorageRequest;
    path: {
        /**
         * Unique workflow identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/storage/workflows/{id}';
};

export type UpdateStorageWorkflowErrors = {
    /**
     * Invalid update payload
     */
    400: ApiErrorResponse;
    /**
     * Workflow not found
     */
    404: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type UpdateStorageWorkflowError = UpdateStorageWorkflowErrors[keyof UpdateStorageWorkflowErrors];

export type UpdateStorageWorkflowResponses = {
    /**
     * Workflow updated successfully
     */
    200: WorkflowStorageItem;
};

export type UpdateStorageWorkflowResponse = UpdateStorageWorkflowResponses[keyof UpdateStorageWorkflowResponses];

export type InstallBrowserBinaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/browser-binaries';
};

export type InstallBrowserBinaryErrors = {
    /**
     * Failed to download browser binary
     */
    500: ApiErrorResponse;
};

export type InstallBrowserBinaryError = InstallBrowserBinaryErrors[keyof InstallBrowserBinaryErrors];

export type InstallBrowserBinaryResponses = {
    /**
     * Chromium binary downloaded and installed successfully
     */
    200: SystemResponse;
};

export type InstallBrowserBinaryResponse = InstallBrowserBinaryResponses[keyof InstallBrowserBinaryResponses];

export type GetSystemMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/metrics';
};

export type GetSystemMetricsResponses = {
    /**
     * System performance metrics sampled successfully
     */
    200: SystemMetricsResponse;
};

export type GetSystemMetricsResponse = GetSystemMetricsResponses[keyof GetSystemMetricsResponses];

export type GetAppSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/settings';
};

export type GetAppSettingsErrors = {
    /**
     * Database query error
     */
    500: ApiErrorResponse;
};

export type GetAppSettingsError = GetAppSettingsErrors[keyof GetAppSettingsErrors];

export type GetAppSettingsResponses = {
    /**
     * Current application and grid settings
     */
    200: AppSettings;
};

export type GetAppSettingsResponse = GetAppSettingsResponses[keyof GetAppSettingsResponses];

export type PatchAppSettingsData = {
    body: UpdateAppSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/system/settings';
};

export type PatchAppSettingsErrors = {
    /**
     * Invalid patch payload
     */
    400: ApiErrorResponse;
    /**
     * Database update error
     */
    500: ApiErrorResponse;
};

export type PatchAppSettingsError = PatchAppSettingsErrors[keyof PatchAppSettingsErrors];

export type PatchAppSettingsResponses = {
    /**
     * Application settings patched successfully
     */
    200: AppSettings;
};

export type PatchAppSettingsResponse = PatchAppSettingsResponses[keyof PatchAppSettingsResponses];

export type UpdateAppSettingsData = {
    body: AppSettings;
    path?: never;
    query?: never;
    url: '/api/v1/system/settings';
};

export type UpdateAppSettingsErrors = {
    /**
     * Invalid settings payload
     */
    400: ApiErrorResponse;
    /**
     * Database write error
     */
    500: ApiErrorResponse;
};

export type UpdateAppSettingsError = UpdateAppSettingsErrors[keyof UpdateAppSettingsErrors];

export type UpdateAppSettingsResponses = {
    /**
     * Application settings replaced successfully
     */
    200: AppSettings;
};

export type UpdateAppSettingsResponse = UpdateAppSettingsResponses[keyof UpdateAppSettingsResponses];

export type OpenWebStudioData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/studio/session';
};

export type OpenWebStudioResponses = {
    /**
     * Web Studio opened successfully in system browser
     */
    200: SystemResponse;
};

export type OpenWebStudioResponse = OpenWebStudioResponses[keyof OpenWebStudioResponses];

export type WsHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ws';
};
