export const conditionsTasks = {
  'repeat-task': {
    name: 'Repeat task',
    icon: 'Repeat',
    component: 'BlockRepeatTask',
    category: 'conditions',
    inputs: 1,
    outputs: 2,
    allowedInputs: true,
    maxConnection: 1,
    refDataKeys: ['repeatFor'],
    data: {
      disableBlock: false,
      repeatFor: '1',
    },
  },
  conditions: {
    name: 'Conditions',
    description: 'Conditional block',
    icon: 'CaseSensitive',
    component: 'BlockConditions',
    editComponent: 'EditConditions',
    category: 'conditions',
    inputs: 1,
    outputs: 0,
    allowedInputs: true,
    maxConnection: 1,
    data: {
      description: '',
      disableBlock: false,
      conditions: [],
      retryConditions: false,
      retryCount: 10,
      retryTimeout: 1000,
    },
  },
  'element-exists': {
    name: 'Element exists',
    description: 'Check if an element is exists',
    icon: 'Crosshair',
    component: 'BlockElementExists',
    editComponent: 'EditElementExists',
    category: 'conditions',
    inputs: 1,
    outputs: 2,
    allowedInputs: true,
    maxConnection: 1,
    refDataKeys: ['selector'],
    data: {
      disableBlock: false,
      description: '',
      findBy: 'cssSelector',
      selector: '',
      tryCount: 1,
      timeout: 500,
      markEl: false,
      throwError: false,
    },
  },
  'while-loop': {
    name: 'While loop',
    description: 'Execute blocks while the condition is met',
    icon: 'RotateCw',
    component: 'BlockBasicWithFallback',
    editComponent: 'EditWhileLoop',
    category: 'conditions',
    inputs: 1,
    outputs: 2,
    allowedInputs: true,
    maxConnection: 1,
    data: {
      disableBlock: false,
      description: '',
      conditions: null,
    },
  },
  'loop-data': {
    name: 'Loop data',
    icon: 'RotateCw',
    component: 'BlockBasic',
    editComponent: 'EditLoopData',
    category: 'conditions',
    inputs: 1,
    outputs: 1,
    allowedInputs: true,
    maxConnection: 1,
    refDataKeys: [
      'maxLoop',
      'loopData',
      'selector',
      'startIndex',
      'variableName',
      'referenceKey',
      'elementSelector',
    ],
    autocomplete: ['variableName', 'loopId'],
    data: {
      disableBlock: false,
      loopId: '',
      maxLoop: 0,
      toNumber: 10,
      fromNumber: 1,
      startIndex: 0,
      loopData: '[]',
      description: '',
      variableName: '',
      referenceKey: '',
      reverseLoop: false,
      elementSelector: '',
      waitForSelector: false,
      waitSelectorTimeout: 5000,
      resumeLastWorkflow: false,
      loopThrough: 'data-columns',
    },
  },
  'loop-elements': {
    name: 'Loop elements',
    icon: 'RotateCcw',
    component: 'BlockBasic',
    editComponent: 'EditLoopElements',
    category: 'conditions',
    inputs: 1,
    outputs: 1,
    allowedInputs: true,
    maxConnection: 1,
    refDataKeys: [
      'maxLoop',
      'selector',
      'variableName',
      'elementSelector',
      'actionElSelector',
    ],
    autocomplete: ['loopId'],
    data: {
      disableBlock: false,
      loopId: '',
      selector: '',
      maxLoop: '0',
      description: '',
      reverseLoop: false,
      actionElSelector: '',
      findBy: 'cssSelector',
      actionElMaxWaitTime: 5,
      actionPageMaxWaitTime: 10,
      loadMoreAction: 'none',
      scrollToBottom: true,
      waitForSelector: false,
      waitSelectorTimeout: 5000,
    },
  },
  'loop-breakpoint': {
    name: 'Loop breakpoint',
    description: 'To tell where loop data must stop',
    icon: 'Square',
    component: 'BlockLoopBreakpoint',
    category: 'conditions',
    disableEdit: true,
    inputs: 1,
    outputs: 1,
    allowedInputs: true,
    maxConnection: 1,
    data: {
      disableBlock: false,
      loopId: '',
      clearLoop: false,
    },
  },
};

export default conditionsTasks;
