export const onlineServicesTasks = {
  'google-sheets': {
    name: 'Google sheets',
    description: 'Read Google Sheets data',
    icon: 'FileSpreadsheet',
    component: 'BlockBasic',
    editComponent: 'EditGoogleSheets',
    category: 'onlineServices',
    inputs: 1,
    outputs: 1,
    allowedInputs: true,
    maxConnection: 1,
    refDataKeys: ['customData', 'range', 'spreadsheetId', 'variableName'],
    autocomplete: ['refKey'],
    data: {
      disableBlock: false,
      range: '',
      refKey: '',
      type: 'get',
      customData: '',
      description: '',
      spreadsheetId: '',
      dataColumn: '',
      saveData: true,
      assignVariable: false,
      variableName: '',
      firstRowAsKey: false,
      keysAsFirstRow: true,
      valueInputOption: 'RAW',
      InsertDataOption: 'INSERT_ROWS',
      dataFrom: 'data-columns',
    },
  },
  'google-sheets-drive': {
    name: 'Google sheets (GDrive)',
    description: 'Read Google Sheets data',
    icon: 'HardDrive',
    component: 'BlockBasic',
    editComponent: 'EditGoogleSheetsDrive',
    category: 'onlineServices',
    inputs: 1,
    outputs: 1,
    allowedInputs: true,
    maxConnection: 1,
    refDataKeys: [
      'customData',
      'range',
      'spreadsheetId',
      'sheetName',
      'variableName',
    ],
    autocomplete: ['refKey'],
    data: {
      disableBlock: false,
      range: '',
      refKey: '',
      type: 'get',
      customData: '',
      description: '',
      spreadsheetId: '',
      dataColumn: '',
      inputSpreadsheetId: 'connected',
      saveData: true,
      sheetName: '',
      assignVariable: false,
      variableName: '',
      firstRowAsKey: false,
      keysAsFirstRow: true,
      valueInputOption: 'RAW',
      InsertDataOption: 'INSERT_ROWS',
      dataFrom: 'data-columns',
    },
  },
  'google-drive': {
    name: 'Google drive',
    description: 'Upload files to Google Drive',
    icon: 'HardDrive',
    component: 'BlockBasic',
    editComponent: 'EditGoogleDrive',
    category: 'onlineServices',
    inputs: 1,
    outputs: 1,
    allowedInputs: true,
    maxConnection: 1,
    refDataKeys: [],
    autocomplete: ['refKey'],
    data: {
      disableBlock: false,
      action: 'upload',
      filePaths: [],
    },
  },
};

export default onlineServicesTasks;
