export const conditionBuilder = {
  valueTypes: [
    {
      id: 'value',
      category: 'value',
      name: 'Value',
      compareable: true,
      data: { value: '' },
    },
    {
      id: 'code',
      category: 'value',
      name: 'Code',
      compareable: false,
      data: { code: '\nreturn true;', context: 'background' },
    },
    {
      id: 'data#exists',
      category: 'value',
      name: 'Data exists',
      compareable: false,
      valueKey: 'dataPath',
      data: { dataPath: '' },
    },
    {
      id: 'element#text',
      category: 'element',
      name: 'Element text',
      compareable: true,
      data: { selector: '' },
    },
    {
      id: 'element#exists',
      category: 'element',
      name: 'Element exists',
      compareable: false,
      data: { selector: '' },
    },
  ],
  compareTypes: [
    { id: 'eq', name: 'Equals', needValue: true, category: 'basic' },
    { id: 'eqi', name: 'Equals (case insensitive)', needValue: true, category: 'basic' },
    { id: 'nq', name: 'Not equals', needValue: true, category: 'basic' },
    { id: 'gt', name: 'Greater than', needValue: true, category: 'number' },
    { id: 'gte', name: 'Greater than or equal', needValue: true, category: 'number' },
    { id: 'lt', name: 'Less than', needValue: true, category: 'number' },
    { id: 'lte', name: 'Less than or equal', needValue: true, category: 'number' },
    { id: 'cnt', name: 'Contains', needValue: true, category: 'text' },
    { id: 'cni', name: 'Contains (case insensitive)', needValue: true, category: 'text' },
    { id: 'nct', name: 'Not contains', needValue: true, category: 'text' },
    { id: 'nci', name: 'Not contains (case insensitive)', needValue: true, category: 'text' },
    { id: 'stw', name: 'Starts with', needValue: true, category: 'text' },
    { id: 'enw', name: 'Ends with', needValue: true, category: 'text' },
    { id: 'rgx', name: 'Match with RegEx', needValue: true, category: 'text' },
    { id: 'itr', name: 'Is truthy', needValue: false, category: 'boolean' },
    { id: 'ifl', name: 'Is falsy', needValue: false, category: 'boolean' },
  ],
};
