name: Publish VS Code Extension

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code & Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies (Root Workspace)
        run: pnpm install --frozen-lockfile

      - name: Package Extension (VSIX)
        working-directory: ./automa-vsce
        run: npx @vscode/vsce package --no-dependencies

      - name: Publish to VS Code Marketplace
        working-directory: ./automa-vsce
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }} --no-dependencies

      - name: Upload VSIX to GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: ./automa-vsce/*.vsix
